backend:
  name: git-gateway
media_folder: "images"
collections:
  - label: "Website Content"
    name: "website-content"
    editor:
      preview: false
    files:
      - label: "Home page"
        name: "home-page"
        file: "index.html"
        fields:
          - { label: "Heading 1", name: "heading1", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "markdown" }
          - { label: "Body", name: "body", widget: "hidden" }
